general:
  ontology: data/go.owl
  graph-gen-method: dl2vec
  
rgcn-params:
  lr: 0.00001
  n-hidden: 1
  batch-size: 32
  epochs: 64
  dropout: 0.3
  num-bases: -1
  normalization: False
  self-loop: True
  min_edges: 1
  seed: 0

files:
  train_inter_file: "data/4932.train_interactions.pkl"
  test_inter_file: "data/4932.test_interactions.pkl"
  data_file: "data/swissprot.pkl"
  output_model: "data/dl2vec_yeast_model.pt"