general:
  ontology: data/go.owl
  graph-gen-method: owl2vec_star
  
rgcn-params:
  lr: 0.004
  n-hidden: 2
  batch-size: 32
  epochs: 32
  dropout: 0.1
  num-bases: -1
  normalization: False
  self-loop: False
  seed: 0

files:
  train_inter_file: "data/4932.train_interactions.pkl"
  test_inter_file: "data/4932.test_interactions.pkl"
  data_file: "data/swissprot.pkl"
  output_model: "data/dl2vec_yeast_model.pt"