name: mowldev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cairo
  - dglteam::dgl
  - numpy
  - networkx
  - click
  - grpcio
  - JPype1
  - owlready2
  - pandas
  - protobuf
  - pytest
  - pyyaml
  - requests
  - scipy
  - scikit-learn
  - urllib3
  - pytorch
  - gensim=3.8.3
  - openjdk
  - gradle
  - rdflib
  - pip
  - pip:
    - pykeen
    - https://github.com/thibaudmartinez/node2vec/releases/download/v0.2.0/node2vec-0.1.0-cp39-cp39-linux_x86_64.whl
  - jupyter
  - ipykernel