name: mowldev
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - cairo
  - dglteam::dgl-cuda11.3
  - numpy
  - networkx
  - click
  - grpcio
  - JPype1
  - owlready2
  - pandas
  - protobuf
  - cudnn
  - cudatoolkit=11.3.*
  - pytest
  - pyyaml
  - requests
  - scipy
  - scikit-learn
  - urllib3
  - pytorch
  - gensim
  - openjdk
  - gradle
  - pip
  - pip:
    - pykeen
  - jupyter
  - ipykernel