name: mowl
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cairo
  - dglteam::dgl
  - numpy
  - networkx
  - click
  - grpcio
  - JPype1
  - owlready2
  - pandas
  - protobuf
  - pytest
  - pyyaml
  - requests
  - scipy
  - scikit-learn
  - urllib3
  - pytorch
  - gensim
  - openjdk
  - gradle
  - pip
  - pip:
    - pykeen
    - https://github.com/thibaudmartinez/node2vec/releases/download/v0.1.0/node2vec-0.1.0-cp37-cp37m-linux_x86_64.whl