name: mowl
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cairo
  - dglteam::dgl
  - matplotlib
  - numpy
  - networkx
  - click
  - grpcio
  - JPype1
  - pandas
  - protobuf
  - pytest
  - pyyaml
  - requests
  - scipy
  - scikit-learn
  - urllib3
  - pytorch
  - gensim
  - openjdk
  - gradle
  - tqdm
  - pip
  - pip:
    - pykeen
