general:
  ontology: data/ppi/go.owl
  graph-gen-method: dl2vec
  use-case: ppi
  
rgcn-params:
  lr: 0.00001
  n-hidden: 3
  batch-size: 128
  epochs: 64
  dropout: 0.5
  regularization: 0.001
  num-bases: -1
  normalization: True
  self-loop: False
  min-edges: 100
  seed: 0

files:
  train_inter_file: "data/ppi/4932.train_interactions.pkl"
  valid_inter_file: "data/ppi/4932.valid_interactions.pkl"
  test_inter_file: "data/ppi/4932.test_interactions.pkl"
  data_file: "data/ppi/4932.annotations.tsv"
  terms_file: "data/ppi/4932.terms.tsv"
  precomputed_edges_file: "data/ppi/4932.edges_dl2vec.pkl"
  output_model: "data/ppi/dl2vec_yeast_model.pt"